import datetime,calendar
import stripe
from django.conf import settings
stripe.api_key = settings.STRIPE_APIKEY
from lib.utils import common

def get_all():
    return stripe.test_helpers.TestClock.list()

def delete_clock(id):
    stripe.test_helpers.TestClock.delete(
        id,
    )

def create_clock():
    date = datetime.datetime.now()
    output = calendar.timegm(date.timetuple())
    clock = stripe.test_helpers.TestClock.create(
        frozen_time=output,
        name="Autogenerated clock " + str(common.random_id())
    )
    return clock

def delete_all():
    clocks = get_all()
    for clock in clocks["data"]:
        delete_clock(clock["id"])