# Generated by Django 4.0.2 on 2022-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
