# Generated by Django 4.0.2 on 2022-03-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_user_connection_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_connection',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
