# Generated by Django 4.0.2 on 2022-03-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_user_connection_sent_by_invitation_sent_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='api_id',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='api_id',
            new_name='api_key',
        ),
    ]
