# Generated by Django 4.0.2 on 2022-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_application_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licenses',
            field=models.IntegerField(default=0),
        ),
    ]
