# Generated by Django 4.0.2 on 2022-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_application_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(default='applications/default.png', upload_to='applications/'),
        ),
    ]
